### ISSUE TITLE
Running test scenarios in mygroup:myartifact:0.1.0-SNAPSHOT ← local failed

### ISSUE THREAD

**Issue by jaloncad** [atomist-rugs/rug-koans-editors#14]
Hi,

I'm having problems running Step1 test in macosx ...

```
@jaloncad~/git/tutorialkoans$ rug edit atomist-rugs:rug-koans-editors:Step1OverwriteWithSolution
Resolving dependencies for atomist-rugs:rug-koans-editors:latest completed
Loading atomist-rugs:rug-koans-editors:0.3.0 into runtime completed
Running editor Step1OverwriteWithSolution of atomist-rugs:rug-koans-editors:0.3.0 completed

→ Project
  ~/git/tutorialkoans/ (31 kb in 10 files)

→ Changes
  ├── .atomist/editors/Step1.rug created 330 bytes
  ├── .atomist/tests/Step1.rt created 689 bytes
  ├── staticprojectfile.txt created 19 bytes
  ├── .atomist/editors/Step1.rug updated 322 bytes
  ├── .atomist/tests/Step1.rt updated 673 bytes
  └── .atomist.yml created 2 kb

Successfully edited project tutorialkoans
@jaloncad~/git/tutorialkoans$ rug test
Resolving dependencies for mygroup:myartifact:0.1.0-SNAPSHOT ← local completed
Loading mygroup:myartifact:0.1.0-SNAPSHOT ← local into runtime completed
Running test scenarios in mygroup:myartifact:0.1.0-SNAPSHOT ← local failed

Some(com.atomist.rug.loader.DecoratingOperationsLoader$DecoratedProjectGenerator@20e6c4dc) (of class scala.Some)
```
Thx,
Juan.

**Comment by cdupuis** [comment]
Hi @jaloncad, please update to Rug CLI 0.21.1. This problem should fixed in that version plus Rug 0.10.0.

**Comment by jaloncad** [comment]
I'm currently using Rug CLI 0.21.0. How do I know which version of Rug I'm using?. Do I need to recreate the koan project? There are lines in .atomist.yml with 0.20.0 version.

@jaloncad~/git/tutorialkoans$ rug -v
rug 0.21.0
atomist/rug-cli.git (git revision d6adaee; last commit 2017-01-18)

Rgds,
Juan.

**Comment by jaloncad** [comment]
I've deleted the rug folder in .m2 repository (where my cli.yml points for local-repository) and I've changed also de manifest.yml located in .atomist/ to use rug [0.10.0,1.0.0). Also creating a new project with `rug generate atomist-rugs:rug-koans-project:NewRugKoansProject tutorialkoans2 artifact_id=koans group_id=es.jaloncad` 

Nothing has changed :(

@jaloncad~/git/tutorialkoans2$ vi .atomist/manifest.yml
@jaloncad~/git/tutorialkoans2$ rug install
Processing dependencies
  Downloading com/atomist/rug/maven-metadata.xml ← rug-types (944 bytes) succeeded
  Downloading com/atomist/rug/0.10.0/rug-0.10.0.pom ← rug-types (17 kb) succeeded
  Downloading com/atomist/rug/0.10.0/rug-0.10.0.jar ← rug-types (3 mb) succeeded
Resolving dependencies for es.jaloncad:koans:0.1.0-SNAPSHOT ← local completed
Loading es.jaloncad:koans:0.1.0-SNAPSHOT ← local into runtime completed
  Created META-INF/maven/es.jaloncad/koans/pom.xml
  Created .atomist/manifest.yml
  Created .atomist/metadata.json
Generating archive metadata completed
  Installed es/jaloncad/koans/0.1.0-SNAPSHOT/koans-0.1.0-SNAPSHOT.zip → /Users/jaloncad/.m2/repository
  Installed es/jaloncad/koans/0.1.0-SNAPSHOT/koans-0.1.0-SNAPSHOT.pom → /Users/jaloncad/.m2/repository
  Installed es/jaloncad/koans/0.1.0-SNAPSHOT/koans-0.1.0-SNAPSHOT-metadata.json → /Users/jaloncad/.m2/repository
Installing archive into local repository completed

→ Archive
  ~/git/tutorialkoans2/.atomist/target/koans-0.1.0-SNAPSHOT.zip (3 kb in 9 files)

Successfully installed archive for es.jaloncad:koans:0.1.0-SNAPSHOT
@jaloncad~/git/tutorialkoans2$ rug test
Resolving dependencies for es.jaloncad:koans:0.1.0-SNAPSHOT ← local completed
Loading es.jaloncad:koans:0.1.0-SNAPSHOT ← local into runtime completed
Running test scenarios in es.jaloncad:koans:0.1.0-SNAPSHOT ← local failed

Some(com.atomist.rug.loader.DecoratingOperationsLoader$DecoratedProjectGenerator@4cd1c1dc) (of class scala.Some)

**Comment by cdupuis** [comment]
Can you try with CLI 0.21.1?

**Comment by jaloncad** [comment]
test SUCCESS 😄 after rug-cli upgrade:

@jaloncad~/git/tutorialkoans$ brew upgrade rug-cli
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /Users/jaloncad/Library in PATH, mode 040777
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
todoman
==> Updated Formulae
gitlab-ci-multi-runner                     qemu                                       vim
opus                                       swiftlint                                  youtube-dl

==> Upgrading 1 outdated package, with result:
atomist/tap/rug-cli 0.21.1
==> Upgrading atomist/tap/rug-cli
==> Downloading https://atomist.jfrog.io/atomist/libs-release/com/atomist/rug-cli/0.21.1/rug-cli-0.21.1-bin.tar.gz
######################################################################## 100.0%
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/rug-cli/0.21.1: 11 files, 24.3M, built in 16 seconds
@jaloncad~/git/tutorialkoans$ rug test
Resolving dependencies for mygroup:myartifact:0.1.0-SNAPSHOT ← local completed
Loading mygroup:myartifact:0.1.0-SNAPSHOT ← local into runtime completed
Executing scenario Step1 should create an empty project with a merged README...
  Testing assertion fileExists(SimpleLiteral(README.md))
  Testing assertion fileContains(SimpleLiteral(README.md),SimpleLiteral(Hello!))
  Testing assertion fileExists(SimpleLiteral(staticprojectfile.txt))
  Testing assertion fileContains(SimpleLiteral(staticprojectfile.txt),SimpleLiteral(Important Content!))
Running test scenarios in mygroup:myartifact:0.1.0-SNAPSHOT ← local completed

Successfully executed 1 of 1 scenarios: Test SUCCESS

Thanks,
Juan.
